easy_admin:
    site_name: 'Les Minots de Ndiémane'
    user:
        display_name: true
        display_avatar: false
    list:

    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Categorys
        User:
            class: App\Entity\User
            label: 'User'
            list:
                title: "Gestion des utilisateurs"
        media_album:
            class: App\Entity\Album
            label: 'Album'
            list:
                title: "Médias: Album"
            form:
                fields:
                    - {property: 'title'}
                    - {property: 'date'}
                    - {property: 'caption'}
        media_picture:
            class: App\Entity\Picture
            label: 'Picture'
            list:
                title: "Médias: Picture"
            form:
                fields:
                    - {property: 'imageFile', type: 'vich_image'}
                    - {property: 'caption'}
                    - {property: 'album'}
    design:
        brand_color: '#FFA813'
