easy_admin:
    site_name: 'Les Minots de Ndiémane'
    user:
        name_property_path: 'username'
        display_name: true
        display_avatar: true
    list:

imports:
    - { resource: easy_admin/user.yaml}
    - { resource: easy_admin/agenda.yaml}
    - { resource: easy_admin/tags.yaml}
    - { resource: easy_admin/media_album.yaml}
    - { resource: easy_admin/media_picture.yaml}
    - { resource: easy_admin/stock_category.yaml}
    - { resource: easy_admin/stock_product.yaml}
    - { resource: easy_admin/design.yaml}
