# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        album_thumb:

            quality: 100

            filters:
                thumbnail: { size: [261, 158], mode: outbound }

        album_show:

            quality: 100

            filters:
                thumbnail: { size: [720, 480], mode: outbound }

        event_show:

            quality: 100

            filters:
                thumbnail: { size: [720, 480], mode: outbound }
