vich_uploader:
  db_driver: orm

  mappings:
      picture:
          uri_prefix:         '%app.path.picture%'
          upload_destination: '%kernel.project_dir%/public%app.path.picture%'
          namer: Vich\UploaderBundle\Naming\UniqidNamer

          inject_on_load: false
          delete_on_update: true
          delete_on_remove: true