easy_admin:
  entities:
    #        # List the entity class name you want to manage
    #        - App\Entity\Product
    #        - App\Entity\Category
    account_management:
      class: App\Entity\AccountManagement
      label: 'AccountManager'
      disabled_actions: ['edit', 'delete']
      list:
        title: "Comptes: Transactions"
        fields:
          - {property: 'id'}
          - {property: 'money', label: 'Montant'}
          - {property: 'updateAt', label: 'Date'}
          - {property: 'updateBy', label: 'Éffectuée par'}
      form:
        fields:
          - {property: 'money', label: 'Montant'}
          - {property: 'account'}