easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Categorys
        agenda:
            class: App\Entity\Event
            label: 'Agenda'
            list:
                title: "Agenda"
                fields:
                    - {property: 'id'}
                    - {property: 'title', label: 'Titre'}
                    - {property: 'date'}
                    - {property: 'event', label: 'Évènement'}
                    - {property: 'imageName', label: 'Image', type: 'image', base_path: '%app.path.picture%' }
                    - {property: 'tags'}
            form:
                fields:
                    - {property: 'title', label: 'Titre'}
                    - {property: 'date'}
                    - {property: 'event', type: 'textarea', label: 'Évènement'}
                    - {property: 'imageFile', type: 'vich_image', label: 'Photo'}
                    - {property: 'tags', type_options: { multiple: true }}
