easy_admin:
  design:
    brand_color: '#FFA813'
    menu:
      - {label: 'Dashboard'}
      - {entity: 'User', label: 'Utilisateurs', icon: 'user'}
      - {entity: 'tags', label: 'Tags', icon: 'tags'}
      - {label: 'Gestion des comptes'}
      - {entity: 'account_management', label: 'Management', icon: 'money-check'}
      - {entity: 'account', label: 'Les comptes', icon: 'piggy-bank'}
      - {label: 'Médias'}
      - {entity: 'media_album', label: 'Albums', icon: 'images'}
      - {entity: 'media_picture', label: 'Photos', icon: 'image'}
      - {label: 'Agenda'}
      - {entity: 'agenda', label: 'Agenda', icon: 'calendar'}
      - {label: 'Gestion des stocks'}
      - {entity: 'stock_product', label: 'Produits', icon: 'barcode'}
      - {entity: 'stock_category', label: 'Catégories', icon: 'archive'}