easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Categorys
        media_album:
            class: App\Entity\Album
            label: 'Album'
            list:
                title: "Médias: Album"
                fields:
                    - {property: 'id'}
                    - {property: 'title', label: 'Titre'}
                    - {property: 'date'}
                    - {property: 'caption', label: 'Description'}
                    - {property: 'pictures', label: 'Photos associées'}
            form:
                fields:
                    - {property: 'title', label: 'Titre'}
                    - {property: 'date'}
                    - {property: 'caption', label: 'Description'}