easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Categorys
        media_picture:
            class: App\Entity\Picture
            label: 'Photo'
            list:
                title: "Médias: Photos"
                fields:
                    - {property: 'id'}
                    - {property: 'imageName', label: 'Image', type: 'image', base_path: '%app.path.picture%'}
                    - {property: 'caption', label: 'Description'}
                    - {property: 'date', label: 'Ajouté le'}
                    - {property: 'album'}
            form:
                fields:
                    - {property: 'imageFile', type: 'vich_image', label: 'Photo'}
                    - {property: 'caption', label: 'Description'}
                    - {property: 'album'}