easy_admin:
    site_name: 'Les Minots de Ndiémane'
    user:
        name_property_path: 'username'
        display_name: true
        display_avatar: true
    list:

    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Categorys
        User:
            class: App\Entity\User
            label: 'Utilisateurs'
            list:
                title: "Les Utilisateurs"
                fields:
                    - {property: 'id'}
                    - {property: 'username', label: 'Pseudo'}
                    - {property: 'password', label: 'Mot de passe'}
            form:
                fields:
                    - {property: 'username', label: 'Pseudo'}
                    - {property: 'password', label: 'Mot de passe'}
        media_album:
            class: App\Entity\Album
            label: 'Album'
            list:
                title: "Médias: Album"
                fields:
                    - {property: 'id'}
                    - {property: 'title', label: 'Titre'}
                    - {property: 'date'}
                    - {property: 'caption', label: 'Description'}
                    - {property: 'pictures', label: 'Photos associées'}
            form:
                fields:
                    - {property: 'title', label: 'Titre'}
                    - {property: 'date'}
                    - {property: 'caption', label: 'Description'}
        media_picture:
            class: App\Entity\Picture
            label: 'Photo'
            list:
                title: "Médias: Photos"
                fields:
                    - {property: 'id'}
                    - {property: 'image', label: 'Image', type: 'image', base_path: '%app.path.picture%'}
                    - {property: 'caption', label: 'Description'}
                    - {property: 'date', label: 'Ajouté le'}
                    - {property: 'album'}
            form:
                fields:
                    - {property: 'imageFile', type: 'vich_image', label: 'Photo'}
                    - {property: 'caption', label: 'Description'}
                    - {property: 'album'}
        agenda:
            class: App\Entity\Event
            label: 'Agenda'
            list:
                title: "Agenda"
                fields:
                    - {property: 'id'}
                    - {property: 'title', label: 'Titre'}
                    - {property: 'date'}
                    - {property: 'event', label: 'Évènement'}
                    - {property: 'image', label: 'Image', type: 'image', base_path: '%app.path.picture%' }
                    - {property: 'tags'}
            form:
                fields:
                    - {property: 'title', label: 'Titre'}
                    - {property: 'date'}
                    - {property: 'event', type: 'textarea', label: 'Évènement'}
                    - {property: 'imageFile', type: 'vich_image', label: 'Photo'}
                    - {property: 'tags', type_options: { multiple: true }}
        stock_category:
            class: App\Entity\Category
            label: 'Catégories'
            list:
                title: "Gestion des stocks : Les Catégories"
                fields:
                    - {property: 'id'}
                    - {property: 'name', label: 'Catégorie'}
                    - {property: 'totalWeight', label: 'Poids total'}
                    - {property: 'totalVolume', label: 'Volume total'}
                    - {property: 'product', label: 'Produits associés'}
        stock_product:
            class: App\Entity\Products
            label: 'Produits'
            list:
                title: "Gestion des stocks : Les Produits"
                fields:
                    - {property: 'id'}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'shape', label: 'État du produit'}
                    - {property: 'weight', label: 'Poid en Kg'}
                    - {property: 'volume',}
                    - {property: 'dlc'}
                    - {property: 'category', label: 'Catégorie'}
                    - {property: 'imageName', label: 'Image', type: 'image', base_path: '%app.path.picture%'}
            form:
                fields:
                    - {property: 'name', label: 'Nom du produit'}
                    - {property: 'shape', label: 'État du produit'}
                    - {property: 'weight', label: 'Poid'}
                    - {property: 'volume'}
                    - {property: 'dlc'}
                    - {property: 'category', label: 'Catégorie'}
                    - {property: 'imageFile', type: 'vich_image', label: 'Photo'}
        tags:
            class: App\Entity\Tag
            label: 'Les Tags'
            list:
                title: "Les Tags"
                fields:
                    - {property: 'id'}
                    - {property: 'name', label: 'Tag'}
            form:
                fields:
                    - {property: 'name', label: 'Nom'}
    design:
        brand_color: '#FFA813'
        menu:
            - {label: 'Dashboard'}
            - {entity: 'User', label: 'Utilisateurs', icon: 'user'}
            - {entity: 'tags', label: 'Tags', icon: 'tags'}
            - {label: 'Médias'}
            - {entity: 'media_album', label: 'Albums', icon: 'images'}
            - {entity: 'media_picture', label: 'Photos', icon: 'image'}
            - {label: 'Agenda'}
            - {entity: 'agenda', label: 'Agenda', icon: 'calendar'}
            - {label: 'Gestion des stocks'}
            - {entity: 'stock_product', label: 'Produits', icon: 'barcode'}
            - {entity: 'stock_category', label: 'Catégories', icon: 'archive'}
