easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Categorys
        stock_category:
            class: App\Entity\Category
            label: 'Catégories'
            list:
                title: "Gestion des stocks : Les Catégories"
                fields:
                    - {property: 'id'}
                    - {property: 'name', label: 'Catégorie'}
                    - {property: 'totalWeight', label: 'Poids total'}
                    - {property: 'totalVolume', label: 'Volume total'}
                    - {property: 'product', label: 'Produits associés'}
