easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Categorys
        stock_product:
            class: App\Entity\Products
            label: 'Produits'
            list:
                title: "Gestion des stocks : Les Produits"
                fields:
                    - {property: 'id'}
                    - {property: 'name', label: 'Nom'}
                    - {property: 'shape', label: 'État du produit'}
                    - {property: 'weight', label: 'Poid en Kg'}
                    - {property: 'volume',}
                    - {property: 'dlc'}
                    - {property: 'category', label: 'Catégorie'}
                    - {property: 'imageName', label: 'Image', type: 'image', base_path: '%app.path.picture%'}
            form:
                fields:
                    - {property: 'name', label: 'Nom du produit'}
                    - {property: 'shape', label: 'État du produit'}
                    - {property: 'weight', label: 'Poid'}
                    - {property: 'volume'}
                    - {property: 'dlc'}
                    - {property: 'category', label: 'Catégorie'}
                    - {property: 'imageFile', type: 'vich_image', label: 'Photo'}