easy_admin:
    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Categorys
        tags:
            class: App\Entity\Tag
            label: 'Les Tags'
            list:
                title: "Les Tags"
                fields:
                    - {property: 'id'}
                    - {property: 'name', label: 'Tag'}
            form:
                fields:
                    - {property: 'name', label: 'Nom'}